#!/bin/bash

if [ $# -ne 4 ]; then
  echo "usage: clang-format-merge %O %A %B %P";
  exit 1
fi

BASE="$1"
OURS="$2"
OTHERS="$3"
REPO_PATH="$4"

ROOT="$(git rev-parse --show-toplevel)"

echo "Merging $REPO_PATH in repo $ROOT"

clang-format "-assume-filename=$REPO_PATH" -i "$BASE" "$OURS" "$OTHERS"

git merge-file -Lcurrent -Lbase -Lothers "$OURS" "$BASE" "$OTHERS"
exit $?
